export function configTemplate(origin: string): string {
  const host = new URL(origin).hostname.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "") || "website";
  return `import { defineMigration, entity, field, website } from "@pom4h/migrate";

export default defineMigration({
  name: ${JSON.stringify(host)},

  source: website(${JSON.stringify(origin)}, {
    discover: ["sitemap", "links"],
    concurrency: 6,
    maxPages: 5_000,
  }),

  entities: [
    entity("page", {
      match: /^(?<path>\\/.*)$/,
      id: ({ url }) => url.pathname === "/" ? "home" : url.pathname.replace(/^\\/|\\/$/g, ""),
      route: ({ url }) => url.pathname,
      fields: {
        title: field.text("h1", { required: false }),
        description: field.attr('meta[name="description"]', "content", { required: false }),
        images: field.list("img[src]", { attribute: "src", absolute: true }),
      },
      assetFields: ["images"],
    }),
  ],

  output: {
    generated: "content/generated",
    resolved: "content/resolved",
    overrides: "content/overrides.ts",
  },

  checks: {
    allowEmpty: false,
    maxRemovedRatio: 0.1,
  },
});
`;
}

export const overridesTemplate = `import { defineOverrides } from "@pom4h/migrate";

export default defineOverrides({
  // page: {
  //   home: {
  //     fields: { title: "A durable improvement" },
  //   },
  // },
});
`;

export const workflowTemplate = `name: Synchronize migration

on:
  workflow_dispatch:
  schedule:
    - cron: "17 4 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: 1.4.0

      - name: Install dependencies
        run: bun install

      - name: Synchronize source
        run: bunx @pom4h/migrate sync --check

      - name: Build replacement
        shell: bash
        run: |
          if bun -e 'const p = await Bun.file("package.json").json(); process.exit(p.scripts?.build ? 0 : 1)'; then
            bun run build
          fi

      - name: Open source-diff pull request
        uses: peter-evans/create-pull-request@v8.1.1
        with:
          branch: migrate/source-sync
          delete-branch: true
          commit-message: "chore(content): synchronize legacy source"
          title: "chore(content): synchronize legacy source"
          body: |
            Generated by \`@pom4h/migrate\`.

            Review the semantic source diff and checks before merging.
          labels: content-sync
`;

export const gitignoreTemplate = `.migrate/raw/
.migrate/state/
*.tmp-*
`;
